version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: build
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: test
          command: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: analyze
          command: npm audit


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test